src/Entity/Sites.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SitesRepository")
 */
class Sites
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom_site;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sorties", mappedBy="sortieSite")
     */
    private $sortie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Participants", mappedBy="siteparticipant")
     */
    private $participant;

    public function __construct()
    {
        $this->sortie = new ArrayCollection();
        $this->participant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }





    public function getNomSite(): ?string
    {
        return $this->nom_site;
    }

    public function setNomSite(string $nom_site): self
    {
        $this->nom_site = $nom_site;

        return $this;
    }

    /**
     * @return Collection|Sorties[]
     */
    public function getSortie(): Collection
    {
        return $this->sortie;
    }

    public function addSortie(Sorties $sortie): self
    {
        if (!$this->sortie->contains($sortie)) {
            $this->sortie[] = $sortie;
            $sortie->setSortieSite($this);
        }

        return $this;
    }

    public function removeSortie(Sorties $sortie): self
    {
        if ($this->sortie->contains($sortie)) {
            $this->sortie->removeElement($sortie);
            // set the owning side to null (unless already changed)
            if ($sortie->getSortieSite() === $this) {
                $sortie->setSortieSite(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Participants[]
     */
    public function getParticipant(): Collection
    {
        return $this->participant;
    }

    public function addParticipant(Participants $participant): self
    {
        if (!$this->participant->contains($participant)) {
            $this->participant[] = $participant;
            $participant->setSiteparticipant($this);
        }

        return $this;
    }

    public function removeParticipant(Participants $participant): self
    {
        if ($this->participant->contains($participant)) {
            $this->participant->removeElement($participant);
            // set the owning side to null (unless already changed)
            if ($participant->getSiteparticipant() === $this) {
                $participant->setSiteparticipant(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;


use App\Entity\Etats;
use App\Entity\Inscriptions;
use App\Entity\Sites;
use App\Entity\Sorties;
use App\Form\SitesType;
use App\Form\SortieType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends Controller
{
    /**
     * @Route("/",name="home")
     */
    public function home(Request $request, EntityManagerInterface $em)
    {
        $like = "";
        $organisateur = "";
        $etat = "";
        $inscrit = "";
        $pasInscrit="";
        $siterecherche="";
        $dateDebut="";
        $dateFin="";
        $rechercheSortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $recherche = $request->query->all();
        if (isset($recherche['organisateur']) && $recherche['organisateur'] == 'on') {
            $organisateur = $this->getUser()->getId();
        }
        if (isset($recherche['passees']) && $recherche['passees'] == 'on') {
            $etat = 2;
        }
        if (isset($recherche['like'])) {
            $like = $recherche['like'];
        }
        if (isset($recherche['inscrit'] ) && $recherche['inscrit']=="on") {
            $inscrit=$this->getUser()->getid();
        }
        if (isset($recherche['pasInscrit'] ) && $recherche['pasInscrit']=="on") {
            $pasInscrit=$this->getUser()->getid();
        }
        if (isset($recherche['site'] )) {
            $siterecherche=$recherche['site'];
        }
        if (isset($recherche['dateDebut'] ) && $recherche['dateDebut'] !="" && isset($recherche['dateFin'] )&& $recherche['dateFin']!="") {
            $dateDebut=$recherche['dateDebut'];
            $dateFin=$recherche['dateFin'];
        }
        $rechercheSortie = $rechercheSortieRepo->recherche($like, $organisateur, $etat,$inscrit,$pasInscrit,$siterecherche,$dateDebut,$dateFin);


        $recherche = $request->query->all();
        $sites1 = new Sites();
        $sitesRepo = $this->getDoctrine()->getRepository(Sites::class);
        $sites = $sitesRepo->findAll();
        $user = $this->getUser();
        $sitesForm = $this->createForm(SitesType::class, $sites1);
        $date = date("d-m-Y");
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->findAll();
        dump($sortie);
        foreach ($sortie as $ti){
            foreach ($ti->getSortieIncription() as $tit)
           dump($tit->getParitcipant() );
        }

        $inscript=0;
        return $this->render("main/home.html.twig", ['date' => $date, 'user' => $user, 'sites' => $sites, 'sitesForm' => $sitesForm, 'sorties' => $rechercheSortie,'ins'=>$inscript]);
    }
}

templates/main/home.html.twig
{% extends ('layout.html.twig') %}
 {% block title %}{{ parent() }} Home{% endblock %}
{% block main %}

    <div class="marge-bottom marge-top text-white DIV container">
        <div class="TRANS marge-bottom marge-top">
            <div class="row container text-left text-white">
                <div class="marge-bottom col-md-4 offset-md-8">Date du jour : {{ date }}</div>
                <div class="marge-bottom col-md-4 offset-md-8">Paticipant : {{ user.prenom }}</div>
            </div>

            <div class="marge-bottom row container"><h3>Filtrer les sorties</h3></div>
            <form action="{{ path('home') }} " method="get">

                <div class="row">

                    <div class="marge-bottom col-6">
                        <div class="marge-bottom row">
                            <div class="col-3"><label for="">Site</label></div>
                            <div class="col-9"><select class="col-12" id="pet-select" name="site">
                                    <option value="">Tous les sites</option>
                                    {% for  site  in sites %}
                                        <option value="{{ site.id }}">{{ site.nomSite }}</option>
                                    {% endfor %}
                                </select></div>
                        </div>
                        <div class="row marge-bottom">
                            <div class="col-3"><label for="">Le nom de la sortie contient</label></div>
                            <div class="col-9"><input class="col-12" name="like" type="text"></div>
                        </div>
                        <div class="row">
                            <div class="col-1"><label for="">Entre</label></div>
                            <div class="col-5"><input class="col-12" name="dateDebut" type="date"></div>
                            <div class="col-1"><label for="">et</label></div>
                            <div class="col-5"><input class="col-12" name="dateFin" type="date"></div>
                        </div>
                    </div>
                    <div class="marge-bottom col-4">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="organisateur" name="organisateur">
                            <label class="custom-control-label" for="organisateur">Sortie dont je suis
                                l'organisateur</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="inscrit" name="inscrit">
                            <label class="custom-control-label" for="inscrit">Sortie auxquelles je suis
                                inscrit(e).</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="pasInscrit" name="pasInscrit">
                            <label class="custom-control-label" for="pasInscrit">Sortie auxquelles je ne suis pas
                                inscrit(e).</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="passees" name="passees">
                            <label class="custom-control-label" for="passees">Sortie passées.</label>
                        </div>
                    </div>
                    <div class="col-2"><input type="submit" class="btn btn-outline-primary " value="Rechercher"></div>
                </div>
            </form>

            <div id="table-wrapper">
                <div id="table-scroll">
                    <table class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Nom de la sortie</th>
                            <th scope="col">Date de la Sortie</th>
                            <th scope="col">Clôture</th>
                            <th scope="col">inscrits/places</th>
                            <th scope="col">Etat</th>
                            <th scope="col">inscrit</th>
                            <th scope="col">Organisateur</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for  sortie in sorties %}
                            {% set insct=0 %}
                            {% set pasinsr=0 %}
                            <tr>
                                <th scope="row">{{ sortie.nom }}</th>
                                <td>{{ sortie.dateDebut |date('d/m/Y') }}</td>
                                <td>{{ sortie.dateCloture |date('d/m/Y') }}</td>
                                <td>{{ sortie.sortieIncription |length }}/{{ sortie.maxInscriptions }}</td>
                                <td>{{ sortie.sortieEtat.libelle }}</td>
                                <td>{% for inst in sortie.sortieIncription %}
                                        {% if sortie.id == inst.sortie.id and inst.paritcipant==(app.user) and insct < 1  %}
                                            {% set insct=insct+1 %}
                                            <h4 class="text-center"><strong> X</strong></h4>
                                            <a href="{{ path('desisterSortie',{'id':sortie.id}) }}"> Se désister</a>
                                        {% elseif pasinsr < 1 %}

                                            <strong>Vous n'êtes pas
                                            inscris.
                                            <br>{% if sortie.sortieIncription |length < sortie.maxInscriptions and sortie.dateCloture < "now"|date() %}
                                        {% else %}<u><a href="{{ path('inscriptionSortie',{'id':sortie.id}) }}">Inscrivez
                                                vous </a></u></strong>{% set pasinsr= pasinsr+1 %}{% endif %}
                                        {% endif %}
                                    {% endfor %}
                                    {% if (sortie.sortieIncription |length) == ins and not sortie.organisateur==(app.user).id %}
                                        <strong>Vous n'êtes pas
                                        inscris.
                                        <br>{% if sortie.sortieIncription |length < sortie.maxInscriptions and sortie.dateCloture < "now"|date() %}
                                    {% else %}<u><a href="{{ path('inscriptionSortie',{'id':sortie.id}) }}">Inscrivez
                                            vous </a></u></strong>{% endif %}
                                    {% endif %}{% if sortie.organisateur==(app.user).id %} vous êtes l'organisteur{% endif %}
                                </td>
                                <td>
                                    <a href="{{ path('profilParticipant',{'id':sortie.organisateur}) }}">{{ sortie.sortieParticipant.pseudo }}</a>
                                </td>
                                <td><a href="{{ path('afficheSortie',{'id':sortie.id}) }}">Afficher </a><br>
                                    {% if sortie.organisateur==(app.User.id) %}
                                        <a href="{{ path('modifieSortie',{'id':sortie.id}) }}"> Modifer</a><br>
                                        <a href="{{ path('annuleSortie',{'id':sortie.id}) }}"> Annuler</a>
                                    {% endif %}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <a href="{{ path('createSortie') }}" class="btn btn-outline-primary">Créer une sortie</a>
    </div>

{% endblock %}