src/Entity/Lieux.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LieuxRepository")
 */
class Lieux
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom_lieu;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $rue;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Villes", inversedBy="ville")
     */
    private $lieux;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sorties", mappedBy="sortie")
     */
    private $noLieux;

    public function __construct()
    {
        $this->noLieux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    
    public function getNomLieu(): ?string
    {
        return $this->nom_lieu;
    }

    public function setNomLieu(string $nom_lieu): self
    {
        $this->nom_lieu = $nom_lieu;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(?string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getLieux(): ?Villes
    {
        return $this->lieux;
    }

    public function setLieux(?Villes $lieux): self
    {
        $this->lieux = $lieux;

        return $this;
    }

    /**
     * @return Collection|Sorties[]
     */
    public function getNoLieux(): Collection
    {
        return $this->noLieux;
    }

    public function addNoLieux(Sorties $noLieux): self
    {
        if (!$this->noLieux->contains($noLieux)) {
            $this->noLieux[] = $noLieux;
            $noLieux->setSortie($this);
        }

        return $this;
    }

    public function removeNoLieux(Sorties $noLieux): self
    {
        if ($this->noLieux->contains($noLieux)) {
            $this->noLieux->removeElement($noLieux);
            // set the owning side to null (unless already changed)
            if ($noLieux->getSortie() === $this) {
                $noLieux->setSortie(null);
            }
        }

        return $this;
    }
}

src/Entity/Sites.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SitesRepository")
 */
class Sites
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom_site;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sorties", mappedBy="sortieSite")
     */
    private $sortie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Participants", mappedBy="siteparticipant")
     */
    private $participant;

    public function __construct()
    {
        $this->sortie = new ArrayCollection();
        $this->participant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }





    public function getNomSite(): ?string
    {
        return $this->nom_site;
    }

    public function setNomSite(string $nom_site): self
    {
        $this->nom_site = $nom_site;

        return $this;
    }

    /**
     * @return Collection|Sorties[]
     */
    public function getSortie(): Collection
    {
        return $this->sortie;
    }

    public function addSortie(Sorties $sortie): self
    {
        if (!$this->sortie->contains($sortie)) {
            $this->sortie[] = $sortie;
            $sortie->setSortieSite($this);
        }

        return $this;
    }

    public function removeSortie(Sorties $sortie): self
    {
        if ($this->sortie->contains($sortie)) {
            $this->sortie->removeElement($sortie);
            // set the owning side to null (unless already changed)
            if ($sortie->getSortieSite() === $this) {
                $sortie->setSortieSite(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Participants[]
     */
    public function getParticipant(): Collection
    {
        return $this->participant;
    }

    public function addParticipant(Participants $participant): self
    {
        if (!$this->participant->contains($participant)) {
            $this->participant[] = $participant;
            $participant->setSiteparticipant($this);
        }

        return $this;
    }

    public function removeParticipant(Participants $participant): self
    {
        if ($this->participant->contains($participant)) {
            $this->participant->removeElement($participant);
            // set the owning side to null (unless already changed)
            if ($participant->getSiteparticipant() === $this) {
                $participant->setSiteparticipant(null);
            }
        }

        return $this;
    }
}

src/Entity/Villes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VillesRepository")
 */
class Villes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nom_ville;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Lieux", mappedBy="lieux")
     */
    private $ville;

    public function __construct()
    {
        $this->ville = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getNomVille(): ?string
    {
        return $this->nom_ville;
    }

    public function setNomVille(string $nom_ville): self
    {
        $this->nom_ville = $nom_ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Lieux[]
     */
    public function getVille(): Collection
    {
        return $this->ville;
    }

    public function addVille(Lieux $ville): self
    {
        if (!$this->ville->contains($ville)) {
            $this->ville[] = $ville;
            $ville->setLieux($this);
        }

        return $this;
    }

    public function removeVille(Lieux $ville): self
    {
        if ($this->ville->contains($ville)) {
            $this->ville->removeElement($ville);
            // set the owning side to null (unless already changed)
            if ($ville->getLieux() === $this) {
                $ville->setLieux(null);
            }
        }

        return $this;
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Etats;
use App\Entity\Inscriptions;
use App\Entity\Sorties;
use App\Entity\Villes;
use App\Form\AnnulerSortieType;
use App\Form\DesinscrirType;
use App\Form\InscriptionSortieType;
use App\Form\ModifierSortieType;
use App\Form\SortieType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


class SortieController extends Controller
{
    /**
     * @Route("/createSortie", name="createSortie")
     */
    public function createSortie(Request $request, EntityManagerInterface $em)
    {
        $sortie = new Sorties();
        $villeRepo = $this->getDoctrine()->getRepository(Villes::class);
        $villes = $villeRepo->findAll();
        $ville = $request->request->all();
        dump($ville);
        $user = $this->getUser();
        $site = $user->getSiteparticipant();
        $nomSite = $site->getNomSite();
        $sortie->setSortieSite($site);
        $sortie->setSortieParticipant($user);
        $sortie->setOrganisateur($user->getId());


        $sortieForm = $this->createForm(SortieType::class, $sortie);
        $sortieForm->handleRequest($request);


        if ($sortieForm->isSubmitted() && $sortieForm->isValid()) {
            if ($sortieForm->get('Enregistrer')->isClicked()) {
                $etatRepo = $this->getDoctrine()->getRepository(Etats::class);
                $etat = $etatRepo->findId(3);
                $sortie->setSortieEtat($etat);
                $em->persist($sortie);
                $em->flush();
                $this->addFlash("success", "Crétation réussie");

                $inscrit = new  Inscriptions();
                $orgSortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
                $orgSortie = $orgSortieRepo->findSortieNonInscritOrganisteur($this->getUser());
                $inscrit->setParitcipant($this->getUser());
                $inscrit->setDateInscription(new \DateTime());
                $inscrit->setSortie($orgSortie);
                $em->persist($inscrit);
                $em->flush();
                return $this->redirectToRoute("home");
            } else {
                $etatRepo = $this->getDoctrine()->getRepository(Etats::class);
                $etat = $etatRepo->findId(4);
                $sortie->setSortieEtat($etat);
                $em->persist($sortie);
                $em->flush();
                $this->addFlash("success", "Crétation réussie");

                $inscrit = new  Inscriptions();
                $orgSortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
                $orgSortie = $orgSortieRepo->findSortieNonInscritOrganisteur($this->getUser());
                $inscrit->setParitcipant($this->getUser());
                $inscrit->setDateInscription(new \DateTime());
                $inscrit->setSortie($orgSortie);
                $em->persist($inscrit);
                $em->flush();
                return $this->redirectToRoute("home");
            }


        }

        return $this->render('sortie/create_sortie.html.twig', ['user' => $user, 'villes' => $villes, "sortieForm" => $sortieForm->createView(), "site" => $nomSite]);
    }


    /**
     * @Route("/inscriptionSortie/{id}", name="inscriptionSortie")
     */
    public function inscriptionSortie($id, Request $request, EntityManagerInterface $em)
    {
        $sortie = new Sorties();
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($id);

        $inscriptionSortieForm = $this->createForm(InscriptionSortieType::class, $sortie);
        $inscriptionSortieForm->handleRequest($request);
        $date = new \DateTime();
        dump($date);
        if ($inscriptionSortieForm->isSubmitted() && $inscriptionSortieForm->isValid()) {
            $inscrit = new Inscriptions();
            $inscrit->setSortie($sortie);
            $inscrit->setDateInscription($date);
            $inscrit->setParitcipant($this->getUser());
            $em->persist($inscrit);
            $em->flush();
            $this->addFlash("success", "Inscription réussie");
            return $this->redirectToRoute("home");
        }

        dump($sortie);
        return $this->render('sortie/inscription_sortie.html.twig', ["inscriptionSortieForm" => $inscriptionSortieForm->createView(), 'sortie' => $sortie]);
    }

    /**
     * @Route("/afficheSortie/{id}", name="afficheSortie")
     */
    public function afficheSortie($id, Request $request)
    {
        $sortie = new Sorties();
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($id);
        $inscRepo = $this->getDoctrine()->getRepository(Inscriptions::class);
        $inscrit = $inscRepo->findAll();

        dump($sortie);
        return $this->render('sortie/affiche_sortie.html.twig', ['sortie' => $sortie, 'inscrit' => $inscrit]);
    }

    /**
     * @Route("/desisterSortie/{id}", name="desisterSortie")
     */
    public function desisterSortie($id, Request $request, EntityManagerInterface $em)
    {
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($id);
        $inscriptionSortieForm = $this->createForm(InscriptionSortieType::class, $sortie);
        $inscriptionSortieForm->handleRequest($request);

        if ($inscriptionSortieForm->isSubmitted() && $inscriptionSortieForm->isValid()) {
            $instRepo = $this->getDoctrine()->getRepository(Inscriptions::class);
            $delete = $instRepo->findinscription($id, $this->getUser());
            dump($delete);
            $em->remove($delete);
            $em->flush();
            $this->addFlash("success", "Désinscription réussie");
            return $this->redirectToRoute("home");
        }

        return $this->render('sortie/desister_sortie.html.twig', ['sortie' => $sortie, 'inscriptionSortieForm' => $inscriptionSortieForm->createView()]);
    }

    /**
     * @Route("/annulerSortie/{id}", name="annuleSortie")
     */
    public function annuleSortie($id, Request $request, EntityManagerInterface $em)
    {
        $sortie = new Sorties();
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($id);
        $allSortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $allSortie = $allSortieRepo->findAll();

        $annulerSortieForm = $this->createForm(AnnulerSortieType::class, $sortie);
        $annulerSortieForm->handleRequest($request);

        if ($annulerSortieForm->get('Enregistrer')->isClicked()) {
            $etatRepo = $this->getDoctrine()->getRepository(Etats::class);
            $etat = $etatRepo->find(3);
            $sortie->setSortieEtat($etat);
            if ($annulerSortieForm->isSubmitted() && $annulerSortieForm->isValid()) {

                $em->persist($sortie);
                $em->flush();
                $this->addFlash("success", "Annulation réussie");
                return $this->redirectToRoute("home");
            }
        }
        dump($sortie);
        return $this->render('sortie/annuler_sortie.html.twig', ['annulerSortieForm' => $annulerSortieForm->createView(), 'sortie' => $sortie, 'allSortie' => $allSortie]);
    }

    /**
     * @Route("/modifierSortie/{id}", name="modifieSortie")
     */
    public function modifierSortie($id, Request $request, EntityManagerInterface $em)
    {

        $sortie = new Sorties();
        $villeRepo = $this->getDoctrine()->getRepository(Villes::class);
        $villes = $villeRepo->findAll();
        $ville = $request->request->all();
        dump($ville);
        $user = $this->getUser();
        $site = $user->getSiteparticipant();
        $nomSite = $site->getNomSite();
        $sortie->setSortieSite($site);
        $sortie->setSortieParticipant($user);
        $sortie->setOrganisateur($user->getId());
        $sortieRepo = $this->getDoctrine()->getRepository(Sorties::class);
        $sortie = $sortieRepo->find($id);
        $etat = new Etats();

        $modifierSortieForm = $this->createForm(ModifierSortieType::class, $sortie);
        $modifierSortieForm->handleRequest($request);


        $lieuForm = $this->createForm(ModifierSortieType::class, $sortie);
        $lieuForm->handleRequest($request);

        if ($modifierSortieForm->get('Supprimer')->isClicked()) {
            $em->remove($sortie);
            $em->flush();
            $this->addFlash("success", "Supression réussie");
            return $this->redirectToRoute("home");
        }
        if ($modifierSortieForm->get('Enregistrer')->isClicked()) {
            $etatRepo = $this->getDoctrine()->getRepository(Etats::class);
            $etat = $etatRepo->find(3);
            $sortie->setSortieEtat($etat);
            if ($modifierSortieForm->isSubmitted() && $modifierSortieForm->isValid()) {

                $em->persist($sortie);
                $em->flush();
                $this->addFlash("success", "Modification réussie");
                return $this->redirectToRoute("home");
            }
        }
        if ($modifierSortieForm->get('Publier')->isClicked()) {
            $etatRepo = $this->getDoctrine()->getRepository(Etats::class);
            $etat = $etatRepo->find(4);
            $sortie->setSortieEtat($etat);
            if ($modifierSortieForm->isSubmitted() && $modifierSortieForm->isValid()) {

                $em->persist($sortie);
                $em->flush();
                $this->addFlash("success", "Modification réussie");
                return $this->redirectToRoute("home");
            }
        }

        return $this->render('sortie/modifier_sortie.html.twig', ['sortie' => $sortie, 'modifierSortieForm' => $modifierSortieForm->createView(), "site" => $nomSite, 'villes' => $villes]);
    }
}

templates/sortie/affiche_sortie.html.twig
{% extends ('layout.html.twig') %}
 {% block title %}{{ parent() }} Afficher Sortie{% endblock %}
{% block main %}
    <div class="marge-bottom marge-top DIV text-white container">

        <div CLASS="marge-bottom row">
            <div class="col-2"><label for="">Nom de la sortie :</label></div>
            <div class="col-2">{{ sortie.nom }}</div>
            <div class="col-2  offset-md-1">Ville organisatrice :</div>
            <div class="col-2">{{ sortie.sortieSite.nomSite }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Date et heure de la sortie :</div>
            <div class="col-2">{{ sortie.dateDebut |date('d/m/Y') }}</div>
            <div class="col-2  offset-md-1">Lieu :</div>
            <div class="col-2">{{ sortie.sortie.nomLieu }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Date limite de l'inscription</div>
            <div class="col-2">{{ sortie.dateCloture |date('d/m/Y') }}</div>
            <div class="col-2  offset-md-1">Rue</div>
            <div class="col-2">{{ sortie.sortie.rue }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Nombre de places :</div>
            <div class="col-2">{{ sortie.maxInscriptions }}</div>
            <div class="col-2  offset-md-1" ><label for="">Code postal :</label></div>
            <div class="col-2">{{ sortie.sortie.lieux.codePostal }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Durée :</div>
            <div class="col-2">{{ sortie.duree }}</div>
            <div class="col-2  offset-md-1">Latitude :</div>
            <div class="col-2">{{ sortie.sortie.latitude }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Description et info :</div>
            <div class="col-2">{{ sortie.infosescriptions }}</div>
            <div class="col-2  offset-md-1">Longitude :</div>
            <div class="col-2">{{ sortie.sortie.longitude }}</div>
        </div>


   <div class="row"> <div id="table-wrapper" class="col-6">
           <div id="table-scroll">
               <table class="table table-bordered table-striped">
                   <thead>
                   <tr>
                       <th scope="col">Pseudo</th>
                       <th scope="col">Nom</th>

                   </tr>
                   </thead>
                   <tbody>
                   {% for  sort in inscrit %}
                       <tr>{% if sort.sortie.id == sortie.id %}
                               <th scope="row"><a href="{{ path('profilParticipant',{'id':sortie.organisateur}) }}">{{ sort.paritcipant.pseudo }}</a></th>
                           {% endif %}
                           {% if sort.sortie.id == sortie.id %}
                               <td>
                                   <h4 class="text-center"><strong>{{ sort.paritcipant.nom }}</strong></h4>
                               </td> {% endif %}
                       </tr>
                   {% endfor %}
                   </tbody>
               </table>
           </div>
       </div>
       <div class="col-2 offset-md-2">
           <button class="btn btn-outline-primary col-12" type="reset"><a href="{{ path('home') }}">Retour</a>
           </button>
       </div></div>
    </div>

{% endblock %}

templates/sortie/annuler_sortie.html.twig
{% extends ('layout.html.twig') %}
 {% block title %}{{ parent() }} Annuler Sortie{% endblock %}
{% block main %}
    <div class="marge-bottom marge-top DIV text-white container">
        <h4 class="text-center mb-4">Annuler une sortie</h4>
        <div CLASS="marge-bottom row">
            <div class="col-2"><label for="">Nom de la sortie :</label></div>
            <div class="col-2">{{ sortie.nom }}</div>
            <div class="col-2  offset-md-1">Ville organissation :</div>
            <div class="col-2">{{ sortie.sortieSite.nomSite }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Date et heure de la sortie :</div>
            <div class="col-2">{{ sortie.dateDebut |date('d/m/Y') }}</div>
            <div class="col-2  offset-md-1">Lieu :</div>
            <div class="col-2">{{ sortie.sortie.rue }}</div>
        </div>
       {% if sortie.organisateur==(app.user).id %} <div>
            {{ form_start(annulerSortieForm) }}
            <div class="row marge-bottom">
                <div class="col-2"><label for=""><u>Motif</u></label></div>
                <div class="col-3">{{ form_widget(annulerSortieForm.motif) }}</div>
            </div>
        </div>
        <div class="row marge-bottom">
            <div class="col-2 offset-md-2">

                {{ form_widget(annulerSortieForm.Enregistrer) }}
                {{ form_end(annulerSortieForm) }}
            </div>{% endif %}
        <div class="col-2 offset-md-2">
            <button class="btn btn-outline-primary col-12" type="reset"><a href="{{ path('home') }}">Retour</a></button>
        </div>
        </div>
    </div>

{% endblock %}

templates/sortie/desister_sortie.html.twig
{% extends ('layout.html.twig') %}
 {% block title %}{{ parent() }} Désinscription Sortie{% endblock %}
{% block main %}
 <div class="marge-bottom marge-top DIV text-white container">
  <h3 class="text-center">Desinscription</h3>
  <div CLASS="marge-bottom row">
   <div class="col-2"><label for="">Nom de la sortie :</label></div>
   <div class="col-2">{{ sortie.nom }}</div>
   <div class="col-2  offset-md-1">Ville organissation :</div>
   <div class="col-2">{{ sortie.sortieSite.nomSite }}</div>
  </div>
  <div CLASS="marge-bottom row">
   <div class="col-2">Date et heure de la sortie :</div>
   <div class="col-2">{{ sortie.dateDebut |date('d/m/Y') }}</div>
   <div class="col-2  offset-md-1">Lieu :</div>
   <div class="col-2">{{ sortie.sortie.nomLieu }}</div>
  </div>
  <div CLASS="marge-bottom row">
   <div class="col-2">Date limite de l'inscription</div>
   <div class="col-2">{{ sortie.dateCloture |date('d/m/Y')}}</div>
   <div class="col-2  offset-md-1">Rue</div>
   <div class="col-2">{{ sortie.sortie.rue }}</div>
  </div>
  <div CLASS="marge-bottom row">
   <div class="col-2">Nombre de places :</div>
   <div class="col-2">{{ sortie.maxInscriptions }}</div>
   <div class="col-2  offset-md-1"Code postal :></div>
   <div class="col-2"></div>
  </div>
  <div CLASS="marge-bottom row">
   <div class="col-2">Durée :</div>
   <div class="col-2">{{ sortie.duree }}</div>
   <div class="col-2  offset-md-1">Latitude :</div>
   <div class="col-2">{{ sortie.sortie.latitude }}</div>
  </div>
  <div CLASS="marge-bottom row">
   <div class="col-2">Description et info :</div>
   <div class="col-2">{{ sortie.infosescriptions }}</div>
   <div class="col-2  offset-md-1">Longitude :</div>
   <div class="col-2">{{ sortie.sortie.longitude }}</div>
  </div>
  <div class="row marge-bottom">
   <div class="col-2 offset-md-2">
    <button class="btn btn-outline-primary col-12" type="reset"><a href="{{ path('home') }}">Annuler</a></button>
   </div>
   {% if sortie.dateCloture > "now"|date() %}
    {{ form_start(inscriptionSortieForm) }}
    <div class="col-2 offset-md-2">
     {{ form_widget(inscriptionSortieForm.Enregistrer) }}
    </div>
    {{ form_end(inscriptionSortieForm) }}
   {% endif %}
  </div>
 </div>

{% endblock %}

templates/sortie/inscription_sortie.html.twig
{% extends ('layout.html.twig') %}
 {% block title %}{{ parent() }} Inscription Sortie{% endblock %}
{% block main %}
    <div class="marge-bottom marge-top DIV text-white container">
<h3 class="text-center">Inscription</h3>
        <div CLASS="marge-bottom row">
            <div class="col-2"><label for="">Nom de la sortie :</label></div>
            <div class="col-2">{{ sortie.nom }}</div>
            <div class="col-2  offset-md-1">Ville organissation :</div>
            <div class="col-2">{{ sortie.sortieSite.nomSite }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Date et heure de la sortie :</div>
            <div class="col-2">{{ sortie.dateDebut |date('d/m/Y') }}</div>
            <div class="col-2  offset-md-1">Lieu :</div>
            <div class="col-2">{{ sortie.sortie.nomLieu }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Date limite de l'inscription</div>
            <div class="col-2">{{ sortie.dateCloture |date('d/m/Y')}}</div>
            <div class="col-2  offset-md-1">Rue</div>
            <div class="col-2">{{ sortie.sortie.rue }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Nombre de places :</div>
            <div class="col-2">{{ sortie.maxInscriptions }}</div>
            <div class="col-2  offset-md-1"Code postal :></div>
            <div class="col-2"></div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Durée :</div>
            <div class="col-2">{{ sortie.duree }}</div>
            <div class="col-2  offset-md-1">Latitude :</div>
            <div class="col-2">{{ sortie.sortie.latitude }}</div>
        </div>
        <div CLASS="marge-bottom row">
            <div class="col-2">Description et info :</div>
            <div class="col-2">{{ sortie.infosescriptions }}</div>
            <div class="col-2  offset-md-1">Longitude :</div>
            <div class="col-2">{{ sortie.sortie.longitude }}</div>
        </div>
    <div class="row marge-bottom">
        <div class="col-2 offset-md-2">
            <button class="btn btn-outline-primary col-12" type="reset"><a href="{{ path('home') }}">Annuler</a></button>
        </div>
        {% if sortie.dateCloture > "now"|date() %}
            {{ form_start(inscriptionSortieForm) }}
            <div class="col-2 offset-md-2">
                {{ form_widget(inscriptionSortieForm.Enregistrer) }}
            </div>
            {{ form_end(inscriptionSortieForm) }}
        {% endif %}
    </div>
    </div>

{% endblock %}